spring:
  application:
    name: first-web-manager

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
#mybatis配置
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto   # 或者删除 id-type 配置

# 文件存储配置
file:
  upload-path: ${user.home}/my-project-uploads/
